version: "3.8"

networks:
  symfony-social-media:

services:
  # nginx
  webserver:
    image: nginx:stable-alpine
    container_name: symfony-social-media-webserver
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    networks:
      - symfony-social-media
  # php
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: symfony-social-media-php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - db
    networks:
      - symfony-social-media
  # mysql
  db:
    image: mariadb:10.7
    container_name: symfony-social-media-db
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socialmedia
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    networks:
      - symfony-social-media
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
      - "8088:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - symfony-social-media
